baseURL = "https://tricht.dev/"
languageCode = "en-us"
title = "Michael van Tricht"
theme = "hugo-coder"
paginate = 10
publishDir = "docs"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[blackfriday]
  hrefTargetBlank = true

[params]
    author = "Michael van Tricht"
    info = "Full Stack Developer"
    description = "Michael van Tricht's personal blog"
    keywords = "blog,developer,personal,resume"
    avatarurl = "https://www.gravatar.com/avatar/849871a025344d191ad9fa458380bf49?s=350"

    favicon_32 = "/images/favicon.ico"
    favicon_16 = "/images/favicon.ico"

    footercontent = ""

    hidecredits = true
    hidecopyright = true

    inverted = true

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/mtricht/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin fa-2x"
    weight = 2
    url = "https://www.linkedin.com/in/michael-van-tricht-a6468927/"
[[params.social]]
    name = "Mail"
    icon = "fa fa-envelope fa-2x"
    weight = 2
    url = "mailto:michael@tricht.dev"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/post/"
[[menu.main]]
    name = "About"
    weight = 1
    url  = "/about/"
